import asyncio
import os
import faiss
import numpy as np
import logging
from backend.storage.vector_store import vector_store

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def remove_synthetic_laws():
    logger.info("Starting cleanup of synthetic laws from FAISS vector store...")
    
    # Reload vector store from disk to ensure we have the latest state
    vector_store.load()
    
    initial_count = len(vector_store.documents)
    logger.info(f"Initial document count: {initial_count}")
    
    # Filter out anything generated by our synthetic bulk_ingestion script
    filtered_docs = []
    filtered_metas = []
    filtered_ids = []
    
    removed_count = 0
    
    for doc, meta, doc_id in zip(vector_store.documents, vector_store.metadatas, vector_store.ids):
        if meta.get("source_name") == "bulk_ingestion":
            removed_count += 1
        else:
            filtered_docs.append(doc)
            filtered_metas.append(meta)
            filtered_ids.append(doc_id)
            
    if removed_count == 0:
        logger.info("No synthetic documents found. Nothing to remove.")
        return
        
    logger.info(f"Identified {removed_count} synthetic documents to remove.")
    
    # Rebuild the FAISS index from scratch
    dim = vector_store.index.d if vector_store.index else 768
    new_index = faiss.IndexFlatL2(dim)
    
    if filtered_docs:
        from backend.ai.embeddings import embedding_engine
        
        # We need to re-embed the valid documents to populate the new FAISS index
        # To avoid massive API calls if there are real docs, we could extract the vectors from the old index
        # but Faiss IndexFlatL2 doesn't map ids to vectors easily without reverse lookup.
        # However, for our few real documents (mock cases, constitution), re-embedding is fast.
        logger.info(f"Re-embedding {len(filtered_docs)} remaining genuine documents...")
        
        # Batch re-embedding
        batch_size = 100
        for i in range(0, len(filtered_docs), batch_size):
            batch_docs = filtered_docs[i:i+batch_size]
            embeddings = embedding_engine.embed_texts(batch_docs)
            embeddings_np = np.array(embeddings).astype('float32')
            new_index.add(embeddings_np)
            
    vector_store.index = new_index
    vector_store.documents = filtered_docs
    vector_store.metadatas = filtered_metas
    vector_store.ids = filtered_ids
    
    # Force save
    vector_store.save()
    
    # Also clean up crawler_catalog.db if any state exists
    db_path = os.path.join(os.path.dirname(__file__), "crawler_catalog.db")
    if os.path.exists(db_path):
        import sqlite3
        conn = sqlite3.connect(db_path)
        c = conn.cursor()
        c.execute("DELETE FROM documents WHERE source='bulk_ingestion'")
        conn.commit()
        conn.close()
        
    logger.info(f"Cleanup finished. Genuine document count: {len(vector_store.documents)}")

if __name__ == "__main__":
    remove_synthetic_laws()
